/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panelwiki;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author FSE
 */
public class Wiki extends javax.swing.JPanel {

    /**
     * Creates new form Wiki
     */
    public Wiki() {
        initComponents();
        lblimage.setIcon(new ImageIcon("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\images\\Selec2.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboDistribuciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblimage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtcampo = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        cboDistribuciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una distribucion", "Bernoulli", "Binomial", "Binomial Negativa", "Geometrica", "Hipergeometrica", "Poisson", "Aproximacion Binomial - Poisson" }));
        cboDistribuciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDistribucionesItemStateChanged(evt);
            }
        });
        cboDistribuciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDistribucionesActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lblimage);

        txtcampo.setBackground(new java.awt.Color(240, 240, 240));
        txtcampo.setColumns(20);
        txtcampo.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        txtcampo.setLineWrap(true);
        txtcampo.setRows(5);
        txtcampo.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtcampo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cboDistribuciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cboDistribuciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboDistribucionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDistribucionesItemStateChanged
        String opcion = cboDistribuciones.getSelectedItem().toString();
        
        File file = null;
        if(opcion == "Selecciona una distribucion"){
            txtcampo.setText("");
            /*
            BufferedImage image = null;
            try {
                image = ImageIO.read(new File("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\images\\Selec2.jpg"));
            } catch (IOException ex) {
                Logger.getLogger(Wiki.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            lblimage.setIcon(new ImageIcon("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\images\\Selec2.jpg"));
            return ;
        }else if(opcion == "Bernoulli"){
            file = new File("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\texts\\Bernoulli.txt");
        }else if(opcion == "Binomial"){
            file = new File("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\texts\\Binomial.txt");
            lblimage.setIcon(new ImageIcon("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\images\\Binomial.jpg"));
        }else if(opcion == "Binomial Negativa"){
            file = new File("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\texts\\Negativa.txt");
        }else if(opcion == "Geometrica"){
            file = new File("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\texts\\Geometrica.txt");
        }else if(opcion == "Hipergeometrica"){
            file = new File("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\texts\\Hipergeometrica.txt");
        }else if(opcion == "Poisson"){
            file = new File("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\texts\\Poisson.txt");
        }else if(opcion == "Aproximacion Binomial - Poisson"){
            file = new File("C:\\Users\\FSE\\Desktop\\panelWiki\\src\\texts\\Aproximacion.txt");
        }
        BufferedReader br = null; 
        try {
            br = new BufferedReader(new FileReader(file));
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error interno del programa: "+ex);
        }
        String st = "",linea; 
        try {
            while ((linea = br.readLine()) != null)
                st+=linea+"\n";
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error interno del programa: "+ex);
        }
        txtcampo.setText(st);
    }//GEN-LAST:event_cboDistribucionesItemStateChanged

    private void cboDistribucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDistribucionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDistribucionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboDistribuciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextArea txtcampo;
    // End of variables declaration//GEN-END:variables
}
